name: New Feature
description: File a new feature for the project.
title: "[Feature] <title>"
labels: ["feature"]
assignees:
  - tegepat
  - winkste
body:
  - type: markdown
    attributes:
      value: | 
        Thank you for taking the time to fill out this feature report!
  - type: textarea
    attributes:
      label: Functional Description
      description: A concise description of the new feature.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Solution and needed Work
      description: A concise description of your expected solution and, if possible, the needed work for the feature.
    validations:
      required: false